SELECT
    MAX(CASE WHEN VARIABLE_NAME = 'Uptime' THEN VARIABLE_VALUE END) AS UPTIME,
    MAX(CASE WHEN VARIABLE_NAME = 'Questions' THEN VARIABLE_VALUE END) AS QUESTIONS,
    MAX(CASE WHEN VARIABLE_NAME = 'Threads_connected' THEN VARIABLE_VALUE END) AS THREADS_CONNECTED,
    MAX(CASE WHEN VARIABLE_NAME = 'Threads_running' THEN VARIABLE_VALUE END) AS THREADS_RUNNING
FROM INFORMATION_SCHEMA.GLOBAL_STATUS
WHERE VARIABLE_NAME IN ('Uptime', 'Threads_connected', 'Questions', 'Threads_running');